# Generated by Django 3.0.5 on 2020-04-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200414_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
    ]
